#!/bin/bash

# clones and updates an automotive sig repo
# $1: branch to be used
# $2: local pristine clone of auto-sig
# $3: alternate tmp directory (if you have faster storage)
# $4: kernel source tarball
# $5: package name
# shellcheck disable=SC2164

autosig_branch=$1;
autosig_cache=$2;
autosig_tmp=$3;
autosig_tarball=$4;
package_name=$5;
stamp_version=$6;
pkgrelease=$7;
use_tags=$8;

redhat=$(dirname "$0")/..;
topdir="$redhat"/..;

# XXX: Placeholders for RHEL variables
rhdistgit_zstream_flag="no"
rtbz=""

function die
{
	echo "Error: $1" >&2;
	exit 1;
}

function upload_sources()
{
	# Uploading the tarball only using CentOS tools
	echo "Cloning the centos common repository";
	git clone https://git.centos.org/centos-git-common.git centos-git-common >/dev/null || die "Unable to clone centos tools";
	./centos-git-common/lookaside_upload -f $autosig_tarball -n $package_name -b $autosig_branch;
}

function update_patches()
{
	# Cloning the source reference repo
	echo "Cloning $package_name source rpm repository";
	git clone -b $autosig_branch ssh://git@git.centos.org/rpms/$package_name $package_name >/dev/null || die "Unable to clone using local cache";

	# Copy all the new sources (including SPEC) except the big tarball, but use it as a reference
	rm -f "${package_name}/SOURCES/*" &> /dev/null; # Replaces everything, git will know if a file changes

	find "$redhat"/rpm/SOURCES/ \( ! -name "*${autosig_tarball#*.}" \) \( ! -name "*gitignore" \) -type f | xargs cp -t "${package_name}/SOURCES/";  &> /dev/null;

	# Remove EMPTY files auto generated by dist-sources
	grep -lrI "# EMPTY" "${package_name}/SOURCES/" | xargs rm -f &> /dev/null;

	mv "${package_name}/SOURCES/kernel.spec" "${package_name}/SPECS/";
	tarball_sha=($(sha1sum $autosig_tarball));
	tarball_name=$(basename -- "$autosig_tarball");

	# Update tarball metada
	echo "$tarball_sha SOURCES/$tarball_name" > "${package_name}/.kernel-automotive.metadata";
}

# Create a stagging repository
date=$(date +"%Y-%m-%d");
tmpdir="$(mktemp -d --tmpdir="$autosig_tmp" AUTOSIG."$date".XXXXXXXX)";

cd "$tmpdir" || die "Unable to create temporary directory";

# upload the sources into centos repos
upload_sources || die "Unable to upload the sources"

# update the centos sources into package repo
update_patches || die "Unable to copy the patches";

echo "Creating diff for review ($tmpdir/diff) and changelog"
# diff the result (redhat/cvs/dontdiff). note: diff reuturns 1 if
# differences were found
diff -X "$redhat"/git/dontdiff -upr "$tmpdir/$package_name" "$redhat"/rpm/SOURCES/ > "$tmpdir"/diff;
# creating the changelog file (no zstream_flag and rtbz)
"$redhat"/scripts/create_distgit_changelog.sh "$redhat"/rpm/SOURCES/kernel.spec \
        "$rhdistgit_zstream_flag" "$package_name" "$rtbz" >"$tmpdir"/changelog

# all done
echo "dist-git updated here: $tmpdir"
