#!/bin/bash

# Script to create PR body
# Arguments: arch build_time total_time passed failed run_id comparison_section repo commit_message_file [build_time_aarch64 total_time_aarch64 passed_aarch64 failed_aarch64]

set -euo pipefail

# Check number of arguments (8-9 for single arch, 13 for multi-arch)
if [ $# -lt 8 ] || ([ $# -gt 9 ] && [ $# -ne 13 ]); then
  echo "Error: Expected 8-9 arguments (single arch) or 13 arguments (multi-arch), got $#" >&2
  echo "Usage: $0 <arch> <build_time> <total_time> <passed> <failed> <run_id> <comparison_section> <repo> [commit_message_file] [build_time_aarch64 total_time_aarch64 passed_aarch64 failed_aarch64]" >&2
  exit 1
fi

ARCH="$1"
BUILD_TIME_X86="$2"
TOTAL_TIME_X86="$3"
PASSED_X86="$4"
FAILED_X86="$5"
RUN_ID="$6"
COMPARISON_SECTION="$7"
REPO="$8"
COMMIT_MESSAGE_FILE="${9:-/tmp/commit_message.txt}"

# Multi-arch parameters (optional)
MULTIARCH=false
if [ $# -eq 13 ]; then
  MULTIARCH=true
  BUILD_TIME_ARM="${10}"
  TOTAL_TIME_ARM="${11}"
  PASSED_ARM="${12}"
  FAILED_ARM="${13}"
fi

# Validate required arguments are not empty
if [ -z "$ARCH" ] || [ -z "$BUILD_TIME_X86" ] || [ -z "$TOTAL_TIME_X86" ] || [ -z "$PASSED_X86" ] || [ -z "$FAILED_X86" ] || [ -z "$RUN_ID" ] || [ -z "$COMPARISON_SECTION" ] || [ -z "$REPO" ]; then
  echo "Error: One or more required arguments are empty" >&2
  echo "Usage: $0 <arch> <build_time> <total_time> <passed> <failed> <run_id> <comparison_section> <repo> [commit_message_file] [build_time_aarch64 total_time_aarch64 passed_aarch64 failed_aarch64]" >&2
  exit 1
fi

# Check if commit message file exists
if [ ! -f "$COMMIT_MESSAGE_FILE" ]; then
  echo "Error: Commit message file not found: $COMMIT_MESSAGE_FILE" >&2
  exit 1
fi

# Convert seconds to minutes for better readability
convert_time() {
  local seconds="${1%s}"  # Remove 's' suffix if present
  local minutes=$((seconds / 60))
  local remaining_seconds=$((seconds % 60))
  echo "${minutes}m ${remaining_seconds}s"
}

BUILD_TIME_X86_READABLE=$(convert_time "$BUILD_TIME_X86")
TOTAL_TIME_X86_READABLE=$(convert_time "$TOTAL_TIME_X86")

if [ "$MULTIARCH" = true ]; then
  BUILD_TIME_ARM_READABLE=$(convert_time "$BUILD_TIME_ARM")
  TOTAL_TIME_ARM_READABLE=$(convert_time "$TOTAL_TIME_ARM")
fi

cat << EOF
## Summary
This PR has been automatically created after successful completion of all CI stages.

## Commit Message(s)

EOF

cat "$COMMIT_MESSAGE_FILE"
echo ""

if [ "$MULTIARCH" = true ]; then
  cat << EOF

## Test Results

### ✅ Build Stage

| Architecture | Build Time | Total Time |
|--------------|------------|------------|
| x86_64 | ${BUILD_TIME_X86_READABLE} | ${TOTAL_TIME_X86_READABLE} |
| aarch64 | ${BUILD_TIME_ARM_READABLE} | ${TOTAL_TIME_ARM_READABLE} |

- [View build logs](https://github.com/${REPO}/actions/runs/${RUN_ID})

### ✅ Boot Verification
- Status: Passed (both architectures)
- [View boot logs](https://github.com/${REPO}/actions/runs/${RUN_ID})

### ✅ Kernel Selftests

| Architecture | Passed | Failed |
|--------------|---------|--------|
| x86_64 | ${PASSED_X86} | ${FAILED_X86} |
| aarch64 | ${PASSED_ARM} | ${FAILED_ARM} |

- [View kselftest logs](https://github.com/${REPO}/actions/runs/${RUN_ID})

${COMPARISON_SECTION}

---
🤖 This PR was automatically generated by GitHub Actions
Run ID: ${RUN_ID}
EOF
else
  cat << EOF

## Test Results

### ✅ Build Stage
- Status: Passed (${ARCH})
- Build Time: ${BUILD_TIME_X86_READABLE}
- Total Time: ${TOTAL_TIME_X86_READABLE}
- [View build logs](https://github.com/${REPO}/actions/runs/${RUN_ID})

### ✅ Boot Verification
- Status: Passed (${ARCH})
- [View boot logs](https://github.com/${REPO}/actions/runs/${RUN_ID})

### ✅ Kernel Selftests (${ARCH})
- **Passed:** ${PASSED_X86}
- **Failed:** ${FAILED_X86}
- [View kselftest logs](https://github.com/${REPO}/actions/runs/${RUN_ID})

${COMPARISON_SECTION}

---
🤖 This PR was automatically generated by GitHub Actions
Run ID: ${RUN_ID}
EOF
fi
