# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_PCI_PWRCTRL)		+= pci-pwrctl-core.o
pci-pwrctl-core-y			:= core.o

obj-$(CONFIG_PCI_PWRCTRL_PWRSEQ)	+= pci-pwrctrl-pwrseq.o

obj-$(CONFIG_PCI_PWRCTRL_SLOT)		+= pci-pwrctrl-slot.o
pci-pwrctrl-slot-y			:= slot.o
