# SPDX-License-Identifier: GPL-2.0
# Makefile for net selftests

TEST_PROGS := \
	dev_addr_lists.sh \
# end of TEST_PROGS

TEST_INCLUDES := \
	../bonding/lag_lib.sh \
	../../../net/forwarding/lib.sh \
	../../../net/lib.sh \
# end of TEST_INCLUDES

include ../../../lib.mk
