# SPDX-License-Identifier: GPL-2.0

TEST_INCLUDES := $(wildcard lib/py/*.py) \
		 ../../net/net_helper.sh \
		 ../../net/lib.sh \

TEST_PROGS := \
	napi_threaded.py \
	netcons_basic.sh \
	ping.py \
	queues.py \
	stats.py \
	shaper.py \
	hds.py \
# end of TEST_PROGS

include ../../lib.mk
