#!/usr/bin/bash

cat owners.yaml | grep email | grep -v "emailLabel:"  | awk ' { print $2 } ' | while read EMAIL
do
	data=$(gitlab_user_oneliner RSfTo7WRuMz7YpxfrUmz $EMAIL)
	if [ "$data" == "[]" ]; then
		echo "account for $EMAIL not found"
	fi
done

