= Red Hat KWF: Quick Start Guide (QSG)


[prarit Feb 5 2021: I can definitely use some help with this document.  I’m too close to the main KWF documentation to offer any sort of sane Quick Start Guide.  If you have any suggestions, or things that should be changed, please feel free to suggest changes!  Thanks :)]

These are simple instructions and command-line examples to start contributing to the Red Hat kernel.  This document is not meant to be an introduction to the Red Hat Kernel Workflow.  Questions on this document likely can be answered in the https://red.ht/kernel_workflow_doc[main KWF documentation].

== Links to Important Docs

https://docs.google.com/document/d/1z8pPGb4OP4Y8pKOG9UmlDlf1IWs-G0NfH7K_fWRLCBg/[What is a GitLab Fork?] +
https://docs.google.com/document/d/15Y8Io4N2gtvt1nn5WzfFtssiKz5vbS7YoBy81XMg9S0[CommitRules] (https://red.ht/kwf_commit_rules[https://red.ht/kwf_commit_rules]) +
https://docs.google.com/document/d/17AIthPv1jCPWc9MdxKFMo55JG4sZERKpeo_uKtiEc8s[Red Hat and GitLab Configuration] +
https://docs.google.com/document/d/145y8pf6tq1-H3GI3ZBmHypqUqZhVb-AsHpXdMhyDYxA/[Gitlab ‘lab’ utility and the Red Hat Kernel] +
https://docs.google.com/document/d/10CGz1kiUiatPiUGDcNvAMEAZNS6_QkJfqOBCDA6b1b4[GitLab ‘bichon’ utility and the Red Hat Kernel] +
https://gitlab.cee.redhat.com/kernel-review/revumatic/[Red Hat Specific ‘revumatic’ tool]

== Useful Hints

. Setup Red Hat Bugzilla Account
** https://bugzilla.redhat.com/createaccount.cgi[https://bugzilla.redhat.com/createaccount.cgi]
. Setup https://docs.google.com/document/d/17AIthPv1jCPWc9MdxKFMo55JG4sZERKpeo_uKtiEc8s/edit#bookmark=id.foj3lmb03es[GitLab]https://docs.google.com/document/d/17AIthPv1jCPWc9MdxKFMo55JG4sZERKpeo_uKtiEc8s/edit#bookmark=id.foj3lmb03es[ account SSO], etc. (https://www.gitlab.com[https://www.gitlab.com])
** Red SSO GitLab Login: https://red.ht/GitLabSSO[https://red.ht/GitLabSSO] 
** Configure account access
*** SSH: https://docs.gitlab.com/ee/ssh/README.html#adding-an-ssh-key-to-your-gitlab-account[https://docs.gitlab.com/ee/ssh/README.html#adding-an-ssh-key-to-your-gitlab-account]
*** API Personal Access Token (PAT) for tools: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html[https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html]
*** Setup https://docs.google.com/document/d/145y8pf6tq1-H3GI3ZBmHypqUqZhVb-AsHpXdMhyDYxA/edit#heading=h.6qv6e1qo2vfr[lab] and https://docs.google.com/document/d/10CGz1kiUiatPiUGDcNvAMEAZNS6_QkJfqOBCDA6b1b4[bichon]
**** RPMs, or installed & compiled from source
**** Run tools and configure (requires API PAT)
. Red Hat namespace for Project(s)
https://red.ht/GitLab[https://red.ht/GitLab] or +
https://gitlab.com/redhat/rhel[https://gitlab.com/redhat/rhel]

. Clone Project
git clone <project SSH>

. Fork Project
git clone <project SSH>; cd project_name +
lab fork # kernel repos take a long time to fork.  Grab a coffee.

** ----Find the name of the fork
git remote -v  | grep <username>

. Create an MR on main
** *BEFORE CREATING A MERGE REQUEST READ THE *https://docs.google.com/document/d/15Y8Io4N2gtvt1nn5WzfFtssiKz5vbS7YoBy81XMg9S0[*CommitRules]*
git checkout -b <branch_name> +
# do work +
git push -u <fork_name> <branch_name> +
lab mr create  [<origin>] # https://docs.google.com/document/d/1_qqRHloFRVAR8tqeqBJz0nrz5R-2DpSOq20gWZ6nikA/[verify the MR information]

*** Outputs a Merge Request URL that contains the MR ID
*** _It is strongly recommended lab users use the lab mr create --draft option to pass the webhook checks, and when successful, remove the Draft status on the MR withcd _
				lab mr edit <mrID> --ready 

. https://docs.google.com/document/d/1gNUkvexDbs_-VKK69RIW7Oz1BsnslNXJFoBcvbw_8no/edit#[Create an MR ]https://docs.google.com/document/d/1gNUkvexDbs_-VKK69RIW7Oz1BsnslNXJFoBcvbw_8no/edit#[against a specific branch] (ie, z-stream)
. Get a list of MRs
bichon # available on main page +
or +
git fetch --all +
lab mr list --all

. Checkout code from an MR
git fetch --all +
lab mr list --all # to find the mrID +
lab mr checkout <mrID>

. Get patches from an MR
git fetch --all +
lab mr checkout <mrIgitnD>cd  +
git-format-patch -<number_of_patches> +
	or +
git-format-patch origin/main	

. View code without checkout
bichon #select MR from main page +
or +
lab mr show --patch

. Show comments on an MR
bichon +
or +
lab mr show <mrID> --comments

. Comment on a MR
** Non-blocking
bichon #select description, and add comment +
or +
lab mr comment <mrID>

** Blocking (ie, NACK)
bichon #select commit, add comment, select ‘Enable replies to comment’ +
or +
lab mr discussion <mrID> +
lab mr reply <mrID>:<comment_id>

. Approve an MR
bichon #select MR and ‘a’ +
or +
lab mr approve <mrID>

. Unapprove an MR (ie, Rescind-Acked-by)
bichon #select MR and ‘A’ +
or +
lab mr unapprove <mrID>

. Close an MR
		lab mr close <mrID>

. https://docs.google.com/document/d/1rlPfueLbE9cNqRu6yh8x4LkJKG2Dn0lH9uDF3iG1J4o/edit#heading=h.yp1gtaa8c6f0[Updating or Fixing an MR]

== Tips and Tricks

. (Ab)use Draft/WIP state. Any Merge Request in Draft state will not generate emails to RHKL.
.. You can open a Merge Request in Draft state, and leave it in that state until you’re happy with everything -- CommitRefs checks, Signoff checks all pass, MR description looks sane, etc. Move the MR to Ready when you’re happy.
.. You can move a Merge Request from Ready back to Draft before you make updates to it. You can push additional commits, force-push modified commits, and update the MR description (add v2: notes) while it’s back in Draft state without generating any emails to RHKL, fix things up as needed, and then again, move to Ready to send emails. This use of Draft state also solves a problem where you want to update both commits and MR description, which when done while the MR is in Ready state, would send both a v2 and a v3.
.. Create your MRs early, in Draft state, and feel free to continuously update them with additional code from upstream until you’re happy with the progress. For example, update your driver to 5.12-rc1 code, but leave the MR in Draft state while you bring in additional code up through 5.12.0 (and maybe even stable releases).

