name: Automated kernel build and test x86_64 and aarch64

name: Kernel CI

on:
  workflow_run:
    workflows: ["Kernel CI - trigger"]
    types: [completed]

jobs:
  kernelCI:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ctrliq/kernel-src-tree/.github/workflows/kernel-build-and-test-multiarch.yml@rnicolescu_test
    with:
      head_sha: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
