name: Trigger Automated kernel build and test (multi-arch)

on:
  push:
    branches:
      - '*_ciq-6.12.y'
      - '*_ciq-6.12.y-*'
      - '*_ciq-6.12.y-next'

jobs:
  kernelCI:
    uses: ctrliq/kernel-src-tree/.github/workflows/kernel-build-and-test-multiarch-trigger.yml@main
    with:
      skip_kabi: true
    secrets: inherit
