name: Automated kernel build and test x86_64 and aarch64

on:
  push:
    branches:
      - '*_ciqlts8_6'
  pull_request:
    branches:
      - '**'
      - '!mainline'

concurrency:
  group: kernel-ci-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  kernelCI:
    uses: ctrliq/kernel-src-tree/.github/workflows/kernel-build-and-test-multiarch-trigger.yml@main
    secrets: inherit
