name: Validate Kernel Commits (diffofdiffs test)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    uses: ctrliq/kernel-src-tree/.github/workflows/validate-kernel-commits.yml@sultan_gha_diffofdiffs
    secrets: inherit
