CSGITURL ?= git+https://git.centos.org/rpms/

# Define the automotive SIG branch
ifeq ("$(DISTRO)", "centos")
  AUTOSIG_BRANCH:="c$(RHEL_MAJOR)s-sig-automotive-main"
endif

# Revision of the latest source added into repository
AUTOGITCOMMIT:=f4804b999b7210d7557395902b52919ceeaa6d81
