CSGITURL ?= git+https://git.centos.org/rpms/

# Define the automotive SIG branch
ifeq ("$(DISTRO)", "centos")
  AUTOSIG_BRANCH:="c$(RHEL_MAJOR)s-sig-automotive-main"
endif

AUTOUSETAGS?=

ifneq ("$(AUTOUSETAGS)", "y")
  # Revision of the latest source added into repository
  AUTOGITREF?=ce27790e9f0721fc6c1c0728afa792f5ea7d3afa
else
  AUTOGITREF?=$(PACKAGE_NAME)-$(STAMP_VERSION)-$(PKGRELEASE)
endif
