CSGITURL ?= git+https://git.centos.org/rpms/

# Define the automotive SIG branch
ifeq ("$(DISTRO)", "centos")
  AUTOSIG_BRANCH:="c$(RHEL_MAJOR)s-sig-automotive-main"
endif

AUTOUSETAGS?=

ifneq ("$(AUTOUSETAGS)", "y")
  # Revision of the latest source added into repository
  AUTOGITREF?=45f0b50746990c17e97ec98d933c10bd02e70719
else
  AUTOGITREF?=$(PACKAGE_NAME)-$(STAMP_VERSION)-$(PKGRELEASE)
endif
