CSGITURL ?= git+https://git.centos.org/rpms/

# Define the automotive SIG branch
ifeq ("$(DISTRO)", "centos")
  AUTOSIG_BRANCH:="c$(RHEL_MAJOR)s-sig-automotive-main"
endif

# Revision of the latest source added into repository
AUTOGITCOMMIT:=abed7a06ad5bc2ddc4aa0f8da3ea909f1d5a8baf
