# dist-git base url in the format used by cbs
CSGITURL ?= git+https://gitlab.com/centos/automotive/rpms/

# Define the default automotive SIG branch (dist-git)
AUTOSIG_BRANCH:="c$(RHEL_MAJOR)s-sig-automotive-main"
