CSGITURL ?= git+https://git.centos.org/rpms/

# Define the automotive SIG branch
ifeq ("$(DISTRO)", "centos")
  AUTOSIG_BRANCH:="c$(RHEL_MAJOR)s-sig-automotive-main"
endif

# Revision of the latest source added into repository
AUTOGITCOMMIT:=6c70bf23cdff07e72ffddcbbb7a747edd5cc2a4f
